ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    print_diagnostics: true
    debug: false
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    # ==============================
    #  WHEEL ODOMETRY (ENCODER)
    # ==============================
    odom0: "/odometry/wheel"

    # Differential robot için:
    #  x,y position = true
    #  yaw orientation = true
    #  vx (linear velocity) = true
    #  wz (angular velocity - yaw rate) = true

    odom0_config:
      [
        false,  false,  false,     # x, y, z position
        false, false, false,      # roll, pitch, yaw orientation
        true,  true, true,     # x, y, z linear velocity (vx = true)
        false, false, true,      # roll, pitch, yaw angular velocity (yaw rate = true)
        false, false, false      # linear acceleration
      ]

    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10


    # ==============================
    # KONTROL GİRİŞİ (cmd_vel kullanmıyoruz)
    # ==============================
    use_control: false


    # ==============================
    #  PROCESS NOISE COVARIANCE
    #  Sistem iç gürültüsü
    # ==============================

    process_noise_covariance: [0.05, 0.05, 0.001, 0.02, 0.02, 0.10, 0.10, 0.10, 0.05, 0.20,  0.20, 0.10, 10.0, 10.0, 10.0]
